### PR TITLE
add create, save, updateOrCreate, destroy, destroyAll method

### PR DESCRIPTION
**Pull request by CCharlieLi**

### CODE REVIEW

**Comment by xavierchow** [comment]
how about this PR? @makara

**Comment by makara** [comment]
On it.

**Comment by makara** [comment]
I copied the CRUD tests from the couchbase connector. Let's get the passed. @CCharlieLi Can you add the delete hooks.

**Comment by xavierchow** [comment]
Just reminder we need to support sentinel from configuration.

**Comment by CCharlieLi** [comment]
@makara Sorry for the late reply, please review.

**Comment by makara** [comment]
Thanks.
- Please don't use Async. You don't need `async.parallel` here; it's already parallel if you fire the destroys right away as they are async already.
- The `destroy` hook is expected to return an "info". See https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/master/lib/couchbase3.js#L202-L209

**Comment by CCharlieLi** [comment]
Alright, updating.

**Comment by CCharlieLi** [comment]
@makara Please have a review.

**Pull request merged**
